#IrcServer:      199.9.250.117:443
#`IrcServer:      irc.twitch.tv:6667

IrcServer:      chat.freenode.net
IrcNick:        tasred
IrcPassword:    passwd
#IrcPassword:    "oauth:hashFromOauthProvider"
IrcChannel:     "#serisium"
#
ReplayPipeName:     replay_pipe
TasbotPipeName:     tasbot_pipe
#
##If true then tasbot's lines are written to tasbotpipe
TasbotPipeEnable:   false
##If true then tasbot's lines are read with espeak
TasbotEspeakEnable: false
#Amount of time to enforce between left presses (in frames)
LeftDelay: 4
