#IrcServer:      199.9.250.117:443
#`IrcServer:      irc.twitch.tv:6667

IrcServer:      chat.freenode.net
IrcNick:        tasred
IrcPassword:    passwd
#IrcPassword:    "oauth:hashFromOauthProvider"
IrcChannel:     "#tasbot"
#
ReplayPipeName:     replay_pipe
TasbotPipeName:     tasbot_pipe
ScreenPlayFileName: RedScreenplayCorrected.txt
#
##If true then tasbot's lines are written to tasbotpipe
TasbotPipeEnable:   true
##If true then tasbot's lines are read with espeak
TasbotEspeakEnable: true
