#Settings for IRC bot

IrcServer:      irc.freenode.net
IrcNick:        TheAxeBot
IrcPassword:    passwd
IrcChannel:     "#lsnes"

ReplayPipeName:     replay_pipe
TasbotPipeName:     tasbot_pipe
ScreenPlayFileName: screenplay.txt
